### ISSUE TITLE
Extra parameters ?

### ISSUE THREAD

**Issue by jbruinaud** [checkmarx-ts/checkmarx-cxflow-github-action#2]
Is there a way to modify/override the application.yml file before it's pushed to the container in order to change the cx version or the target ticketing system ?

**Comment by kmcdon83** [comment]
@jbruinaud , any of the yml properties can be overridden/added by using the params input for the action:
https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/blob/master/action.yml#L45

For example:
```
any:
  value: XXXX
  other-value: XXXXX
```
would be the following  in your action:
```
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0
      with:
        project: GithubActionTest
        team: '\CxServer\SP\Checkmarx'
        checkmarx_url: ${{ secrets.CHECKMARX_URL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        params:  --any.value=newvalue --any.other-value=newvalue2
```
