### ISSUE TITLE
Feature Request: Custom fields

### ISSUE THREAD

**Issue by ebickle** [checkmarx-ts/checkmarx-cxflow-github-action#22]
Our CxSAST is configured to have a customized field for each project that allows us to tag them with the corporate "platform"  that they correspond to. These platform tags are then used to correlate vulnerabilities and build enterprise dashboards for VPs / senior leadership.

If possible, we'd like the ability to assign CxSAST custom fields to projects via the GitHub action. 

For example:
```
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
      with:
        project: GithubActionTest
        team: '/CxServer/SP/Checkmarx'
        custom-fields: 
            mycustomfield: fieldvalue 
```

Also worth noting that the GitHub's convention for Action parameter names is to use dashes instead of underscores - something to consider going forward :)
