### ISSUE TITLE
Failed to bind properties under 'cx-flow.scan-resubmit' to boolean

### ISSUE THREAD

**Issue by shyam-ks** [checkmarx-ts/checkmarx-cxflow-github-action#48]
While passing cx-flow.scan-resubmit in params giving following error. 
```
Run checkmarx-ts/checkmarx-cxflow-github-action@v1.4
  with:
    project: s1e-usermgmt-svc
    team: /CxSer
    preset: Bently Nevada - All
    github_token: ***
    checkmarx_url: https://xxxxxxxxxxxxx/
    checkmarx_username: ***
    checkmarx_password: ***
    break_build: true
    scanners: sast
    bug_tracker: Sarif
    app: s1e-usermgmt-svc
    params: --namespace=ns --repo-name=ss-svc --branch=refs/heads/develop --cx-flow.zip-exclude="\.git\/.*,\.github\/.*,tests\/.*,.+\/tests\/.*" --checkmarx.configuration="Improved Scan Flow" --checkmarx.client-secret=453-B7B3-9563627C --cx-flow.filterSeverity "High,Medium" --cx-flow.scan-resubmit true --cx-flow.filter-state "Urgent,Confirmed,To Verify"
    incremental: true
    sca_api_url: https://api.scacheckmarx.com/
    sca_app_url: https://sca.scacheckmarx.com/
    sca_access_control_url: https://platform.checkmarx.net/
    cxgo_base_url: https://api.checkmarx.net/
    cxgo_portal_url: https://cloud.checkmarx.net/
    java_opts: -XX:MaxRAMPercentage=75.0
```

```
Description:

Failed to bind properties under 'cx-flow.scan-resubmit' to boolean:

    Property: cx-flow.scan-resubmit
    Value: 
    Origin: "cx-flow.scan-resubmit" from property source "commandLineArgs"
    Reason: failed to convert java.lang.String to boolean (caused by java.lang.IllegalArgumentException: A null value cannot be assigned to a primitive type)

Action:

Update your application's configuration
```
